{
 "title": "Weather Monitoring",
 "description": "Weather monitoring dashboard",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "stationId",
    "label": "Station ID",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(bucket: \"home\", tag: \"stationId\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Total production",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"home\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"weather\" and r.stationId == \"$stationId\" and r._field == \"totalEnergy\") |> aggregateWindow(every: $__interval, fn: mean) |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"home\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"weather\" and r.stationId == \"$stationId\" and r._field == \"totalEnergyToday\") |> aggregateWindow(every: $__interval, fn: mean) |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Total Energy month",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"home\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"weather\" and r.stationId == \"$stationId\" and r._field == \"totalEnergyToday\") |> aggregateWindow(every: 1d, fn: mean) |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Wind Turbine Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"home\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"weather\" and r.stationId == \"$stationId\" and r._field == \"power\") |> aggregateWindow(every: $__interval, fn: mean) |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Total Energy year",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"home\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"weather\" and r.stationId == \"$stationId\" and r._field == \"totalEnergyToday\") |> aggregateWindow(every: 1w, fn: mean) |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "from(bucket: \"home\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"weather\" and r.stationId == \"$stationId\" and r._field == \"windSpeed\") |> aggregateWindow(every: $__interval, fn: mean) |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"home\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"weather\" and r.stationId == \"$stationId\" and r._field == \"temperature\") |> aggregateWindow(every: $__interval, fn: mean) |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}